# Generated by Django 3.2.25 on 2025-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snm', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=50)),
            ],
        ),
    ]
